name: release
on:
  push:
    tags:
      - 'releases/stable-*'
      - 'releases/test-release/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # call other workflows
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run tests
        env:
          TEST_ELO_IX_URL: ${{ secrets.TEST_ELO_IX_URL }}
          TEST_ELO_IX_USER: ${{ secrets.TEST_ELO_IX_USER }}
          TEST_ELO_IX_PASSWORD: ${{ secrets.TEST_ELO_IX_PASSWORD }}
        run: poetry run python -m unittest discover test
      - name: Build documentation
        run: make html SPHINXBUILD="poetry run sphinx-build"
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: _build/html
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to githubpages
          uses: actions/upload-pages-artifact@v3
          with:
            artifact_name: documentation
            token: ${{ secrets.GITHUB_TOKEN }}